load('/Volumes/FELIPELOPEZ/Run_5/accuracy_classes.mat')
load('/Volumes/FELIPELOPEZ/Run_5/Classes.mat')
load('/Volumes/FELIPELOPEZ/Run_5/time_classes.mat')
%%
figure('Units', 'pixels', ...
    'Position', [100 100 500 375]);
hold on;

hacc  = line(Classes  , accuracy_classes );
hold on;
% htime = line(Classes  , time_classes );

set(hacc                          , ...
  'Color'           , [0 0 .5]    , ...
  'Marker'          , '.'         , ...
  'Color'           , [.3 .3 .3]  );

set(hacc                          , ...
  'LineWidth'       , 2           );
set(hacc                           , ...
  'LineWidth'       , 1           , ...
  'Marker'          , 'o'         , ...
  'MarkerSize'      , 5           , ...
  'MarkerEdgeColor' , [.2 .2 .2]  , ...
  'MarkerFaceColor' , [.7 .7 .7]  );

hTitle  = title ('Accuracy value for different number of classes');
hXLabel = xlabel('Number of classes'                     );
hYLabel = ylabel('Accuracy (%)'                      );

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');

set([hXLabel, hYLabel]  , ...
    'FontSize'   , 10          );
set( hTitle                    , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 30:5:100, ...
  'LineWidth'   , 1         );


%%
figure('Units', 'pixels', ...
    'Position', [100 100 500 375]);
hold on;

hacc  = line(Classes  , time_classes );
hold on;
% htime = line(Classes  , time_classes );

set(hacc                          , ...
  'Color'           , [0 0 .5]    , ...
  'Marker'          , '.'         , ...
  'Color'           , [.3 .3 .3]  );

set(hacc                          , ...
  'LineWidth'       , 2           );
set(hacc                           , ...
  'LineWidth'       , 1           , ...
  'Marker'          , 'o'         , ...
  'MarkerSize'      , 5           , ...
  'MarkerEdgeColor' , [.2 .2 .2]  , ...
  'MarkerFaceColor' , [.7 .7 .7]  );

hTitle  = title ('Computational cost for different number of classes');
hXLabel = xlabel('Number of classes'                     );
hYLabel = ylabel('Time (s)'                      );

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');

set([hXLabel, hYLabel]  , ...
    'FontSize'   , 10          );
set( hTitle                    , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:100:900, ...
  'LineWidth'   , 1         );



%% 
load('/Volumes/FELIPELOPEZ/Run_&/accuracy_Train.mat')
load('/Volumes/FELIPELOPEZ/Run_&/time_Train.mat')
load('/Volumes/FELIPELOPEZ/Run_&/Train.mat')

figure('Units', 'pixels', ...
    'Position', [100 100 500 375]);
hold on;

hacc  = line(Train  , accuracy_Train );
hold on;
% htime = line(Classes  , time_classes );

set(hacc                          , ...
  'Color'           , [0 0 .5]    , ...
  'Marker'          , '.'         , ...
  'Color'           , [.3 .3 .3]  );

set(hacc                          , ...
  'LineWidth'       , 2           );
set(hacc                           , ...
  'LineWidth'       , 1           , ...
  'Marker'          , 'o'         , ...
  'MarkerSize'      , 5           , ...
  'MarkerEdgeColor' , [.2 .2 .2]  , ...
  'MarkerFaceColor' , [.7 .7 .7]  );

hTitle  = title ('Accuracy for different sizes of training set');
hXLabel = xlabel('Number of training images'                     );
hYLabel = ylabel('Accuracy (%)'                      );

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');

set([hXLabel, hYLabel]  , ...
    'FontSize'   , 10          );
set( hTitle                    , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 25:5:50, ...
  'LineWidth'   , 1         );



figure('Units', 'pixels', ...
    'Position', [100 100 500 375]);
hold on;

hacc  = line(Train  , time_Train );
hold on;
% htime = line(Classes  , time_classes );

set(hacc                          , ...
  'Color'           , [0 0 .5]    , ...
  'Marker'          , '.'         , ...
  'Color'           , [.3 .3 .3]  );

set(hacc                          , ...
  'LineWidth'       , 2           );
set(hacc                           , ...
  'LineWidth'       , 1           , ...
  'Marker'          , 'o'         , ...
  'MarkerSize'      , 5           , ...
  'MarkerEdgeColor' , [.2 .2 .2]  , ...
  'MarkerFaceColor' , [.7 .7 .7]  );

hTitle  = title ('Computational cost for different sizes of training set');
hXLabel = xlabel('Number of training images'                     );
hYLabel = ylabel('Time (s)'                      );

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');

set([hXLabel, hYLabel]  , ...
    'FontSize'   , 10          );
set( hTitle                    , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 40:10:140, ...
  'LineWidth'   , 1         );













